### ISSUE TITLE
Switch the repo and the root dir to 'openasip'

### ISSUE THREAD

**Issue by pjaaskel** [cpc/openasip#164]
Add a link from the tce repo.

**Comment by sarahec** [comment]
Do you have a list of tasks? Anything we (the community) can help with?

**Comment by pjaaskel** [comment]
Hi @sarahec, your offers for a helping hand is extremely appreciated! Luckily, our @karihepola has made great progress and LLVM 15 should now work so we are nearing the point we can branch the release. At this point the best help would be community testers to shave off the most apparent issues which are not so easily found by the "near-sighted" core developers.
