### ISSUE TITLE
Question about tooling

### ISSUE THREAD

**Issue by robertkeizer** [cpc/openasip#183]
Heyo - quick question; I'm experimenting with `openasip` ( thanks ), and have got a rudimentary docker image going that contains the toolchain passing tests ( https://github.com/reconfigurable/openasip ) .

It's really rough right now, and I'm exposing the graphical interface over `x11vnc`.

Is this something I should clean up and create a PR back into `openasip` proper?

Basically asking if there would be any appetite for a `Dockerfile` and related scripts being included in the project itself.

**Comment by pjaaskel** [comment]
Yes, it would be definitely helpful to other users. Thanks in advance!

**Comment by robertkeizer** [comment]
Any back and forth around the implementation of this can be done over in #190 - closing this issue.
