### ISSUE TITLE
Issue in Further acceleration by adding custom operation to large TTA

### ISSUE THREAD

**Issue by Jedrek09** [cpc/openasip#273]
After adding the reflecter FU from the tour.hdb like done earlier and Fully connecting the IC and running 

tcecc -O3 -a large_custom.adf -o crc_with_custom_op.tpef -k result -k test crc_with_custom_op.c
main.c

I get the following error 
error: call to undefined function 'main'.
main.c: command not found

the code compiled crc_with_custom_op.c and main.c together but there is specified only one source file (crc_with_custom_op.c) in the command. It is needed to include both source files in the compilation command.

Am I correct?

**Comment by pjaaskel** [comment]
You should add the main.c to the tcecc command line, not to the next line.
